config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { 
    sessions: 'users/sessions', 
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  # as :user do
  #   get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
  #   get "users/sign_up" => "devise/registrations#new" # custom path to sign_up/registration
  #   get 'users/edit' => 'devise/registrations#edit', :as => 'welcome/edit'
  #   put 'users' => 'devise/registrations#update', :as => 'welcome/update'
  # end

  get 'welcome/index'
  get 'welcome/eligible'
  get 'welcome/choose'
  get 'welcome/register'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def contact
  end

  def eligible
  end

  def choose
  end

  def setup
  end

  def edit
  end

  def update
  end

  def register
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--<title>HomePathRewards</title>-->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="apple-touch-icon" sizes="57x57" href="apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
    <link rel="manifest" href="manifest.html">

  </head>

  <body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%=link_to image_tag("logo_nav_h.png", border: 0), welcome_index_path %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Am I Eligible", welcome_eligible_path %></li>
            <li><%= link_to "Get My Check", welcome_register_path %></li>
            <!--<li><%= link_to "Login", welcome_choose_path %></li>-->
            <% if user_signed_in? %>
              <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
              <!--<li>Logged in as <%= current_user.email %></li>-->
            <% else %>
              <!--<li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>-->
              <li><%= link_to "Login", user_session_path, :class => 'navbar-link'  %></li>
            <% end %>
          </ul>
        </div>
        <!--<div>
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
        </div>-->
      </div>
    </div>

    <%= yield %>

    <div class="container">
    <div class="footer-img">
      <div class="row no-margin">
        <div class="col-xs-12 no-padding">
          <picture>
            <source media="(max-width: 600px)" srcset="app/assets/images/footer-home-mobile.jpg">
            <%= image_tag "rochestor_carousal.jpg" %>
          </picture>
        </div>
      </div>
    </div>
    <footer class="bg-dk-gray text-center">
      <div class="row no-margin">
        <div class="col-xs-12 ">
          <p class="font-larger">This exclusive offer is not available to the general public. It is available only to households who are members and customers of selected partners of HomePathRewards.</p>
          <p class="font-light">HomePathRewards incentives apply  only to the purchase or sale of your home from participating realtors/lender/title companies.  Any home previously sold, registered or titled is not eligible. Offers vary by home, purchase date, and purchase type. Refer to "Choose My Perfect Home" section for details on how much cash back you can receive. For purchases of Fiat Chrysler Automobiles (Chrysler, Dodge, Fiat, Jeep, Ram), offers vary by purchase date and require documentation of vehicle ownership that is not a Fiat-Chrysler product (passenger cars and trucks only). All qualified Hyundai purchases are eligible for $500 cash incentive except for any vehicle purchased under the “Hyundai Circle” program in which the total award is $100. Offer available on retail vehicle sales only.  Not available for commercial or other fleet vehicles. Applications must be submitted within 60 days of your vehicle purchase. Offer expires March 31, 2019. This limited time offer and can be cancelled at any time without notice and approval is not guaranteed for any applicant. This incentive is only available on vehicles sold by dealers of listed automotive brands within the 50 United States of America and the District of Columbia.  Vehicles purchased in Guam, Puerto Rico or other US territories are not eligible. Void where prohibited.  See Terms and Conditions for other important information about the program.</p>
          <p class="orange ">&copy; 2018 HomePathRewards | <a href="Home/PrivacyPolicy.html">Privacy Policy</a> | <a href="Home/TermsConditions.html">Terms of Service</a></p>
          <p><em>Robertson homes are registered trademarks of RHomes LLC. RHome® is a registered trademark of RH S.p.A., used under license by RHomes US LLC.</em></p>

          <picture>
            <source media="(max-width: 400px)" srcset="app/assets/images/logo-footer.png">
            <source media="(max-width: 480px)" srcset="app/assets/images/logo-footer-mobile.png">
            <%= image_tag "logo_nav_h.png" %>
          </picture>

        </div>
      </div>
    </footer>
    </div>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), :class=>"orange" %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), :class=>"orange" %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), :class=>"orange" %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/choose.html.erb
<!DOCTYPE html>

<html>

<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<head>
  <title>Choose realtor, lender and title company for best rewards</title>
</head>
<body>

<div class="container">
  <div class="header-image">
    <picture>
      <source media="(max-width: 600px)" srcset="/Content/Images/V2/header-ram-mobile.jpg">
      <%= image_tag "eligible_1024.jpg" %>
    </picture>
    <div class="header-scroll-overlay-container">
      <div id="header-scroll-overlay" class="text-center">
        <p>SCROLL TO SEE MORE<br /><%= image_tag "chevrons.png" %></p>
      </div>
    </div>
  </div>

  <div class="row no-margin">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1 text-center">
      <div class="vehicle-content">
        <h1 class="orange">CHOOSE YOUR PERFECT HOME</h1>
        <p class="light">Search for eligible home from RBHome, Realtor®, HowardHanna®, Century21®, or KellerWilliams.</p>
      </div>
    </div>
  </div>

  <div class="vehicle-filter bg-lt-md-gray">
    <div class="row no-margin">
      <div class="col-xs-12 col-sm-6">
        <div class="row">
          <div class="col-xs-12 col-sm-6">
            <div class="row">
              <div class="col-xs-6 col-sm-12 equal filter-margin"><label><strong>MANUFACTURER</strong></label></div>

            </div>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="row">
              <div class="col-xs-6 col-sm-12 equal filter-margin"><input class="input-checkbox chkMake" id="ChkChrysler" name="ChkChrysler" type="checkbox" value="true" /><input name="ChkChrysler" type="hidden" value="false" /><label for="ChkChrysler">CHRYSLER</label></div>
              <div class="col-xs-6 col-sm-12 equal filter-margin"><input class="input-checkbox chkMake" id="ChkDodge" name="ChkDodge" type="checkbox" value="true" /><input name="ChkDodge" type="hidden" value="false" /><label for="ChkDodge">DODGE</label></div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="row">
          <div class="col-xs-12 col-sm-6">
            <div class="row">
              <div class="col-xs-6 col-sm-12 equal filter-margin"><input class="input-checkbox chkMake" id="ChkJeep" name="ChkJeep" type="checkbox" value="true" /><input name="ChkJeep" type="hidden" value="false" /><label for="ChkJeep">JEEP</label></div>
              <div class="col-xs-6 col-sm-12 equal filter-margin"><input class="input-checkbox chkMake" id="ChkRam" name="ChkRam" type="checkbox" value="true" /><input name="ChkRam" type="hidden" value="false" /><label for="ChkRam">RAM</label></div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="row">
              <div class="col-xs-6 col-sm-12 equal filter-margin"><input class="input-checkbox chkMake" id="ChkFiat" name="ChkFiat" type="checkbox" value="true" /><input name="ChkFiat" type="hidden" value="false" /><label for="ChkFiat">FIAT</label></div>
              <div class="col-xs-6 col-sm-12 equal filter-margin"><input class="input-checkbox chkMake" id="ChkHyundai" name="ChkHyundai" type="checkbox" value="true" /><input name="ChkHyundai" type="hidden" value="false" /><label for="ChkHyundai">HYUNDAI</label></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="vehicle-filter bg-lt-gray">
    <div class="row no-margin">
      <div class="col-xs-12 col-sm-6">
        <div class="row">
          <div class="col-xs-12 col-sm-6">
            <div class="row">
              <div class="col-xs-6 col-sm-12 equal filter-margin"><label><strong>VEHICLE TYPE</strong></label></div>

            </div>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="row">
              <div class="col-xs-6 col-sm-12 equal filter-margin"><input class="input-checkbox chkCategory" id="ChkCar" name="ChkCar" type="checkbox" value="true" /><input name="ChkCar" type="hidden" value="false" /><label for="ChkCar">CARS</label></div>
              <div class="col-xs-6 col-sm-12 equal filter-margin"><input class="input-checkbox chkCategory" id="ChkTruck" name="ChkTruck" type="checkbox" value="true" /><input name="ChkTruck" type="hidden" value="false" /><label for="ChkTruck">TRUCKS</label></div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="row">
          <div class="col-xs-12 col-sm-6">
            <div class="row">
              <div class="col-xs-6 col-sm-12 equal filter-margin"><input class="input-checkbox chkCategory" id="ChkSUV" name="ChkSUV" type="checkbox" value="true" /><input name="ChkSUV" type="hidden" value="false" /><label for="ChkSUV">SUVS &amp; CROSSOVERS</label></div>
              <div class="col-xs-6 col-sm-12 equal filter-margin"><input class="input-checkbox chkCategory" id="ChkVan" name="ChkVan" type="checkbox" value="true" /><input name="ChkVan" type="hidden" value="false" /><label for="ChkVan">VANS</label></div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="row">
              <div class="col-xs-6 col-sm-12 equal filter-margin"><input class="input-checkbox chkCategory" id="ChkConvertible" name="ChkConvertible" type="checkbox" value="true" /><input name="ChkConvertible" type="hidden" value="false" /><label for="ChkConvertible">CONVERTIBLES</label></div>
              <div class="col-xs-6 col-sm-12 equal filter-margin"><input class="input-checkbox chkCategory" id="ChkHybrid" name="ChkHybrid" type="checkbox" value="true" /><input name="ChkHybrid" type="hidden" value="false" /><label for="ChkHybrid">HYBRIDS &amp; ELECTRIC</label></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="row no-margin">
    <div class="col-sm-12 margin-top-30">
      <div id="FCA-Message">
        <p>SPECIAL HomePathRewards OFFERS:</p>
        <p>All qualifying Fiat-Chrysler purchases (Chrysler, Dodge, Fiat, Jeep and Ram branded vehicles) receive $500 for any purchase made on or before March 31, 2018</p>
        <p>All qualifying Fiat-Chrysler purchases made on or after the date of April 1, 2018 receive $250.  Purchaser must show 1) proof of ownership of a non Fiat-Chrylser vehicle in the household; OR 2) proof that the vehicle used at trade in was not a vehicle made by Fiat-Chrysler Automobiles.</p>
      </div>
      <div id="Hyundai-Message">
        <p>SPECIAL HomePathRewards OFFERS:</p>
        <p>All qualifying Hyundai purchases receive $500 except for any purchases made within the "Hyundai Circle" program; those buyers receive $100 back.</p>
      </div>
    </div>
    <div class="col-sm-12" id="vehicle-results">



    </div>
  </div>

  <a id="back-to-top" href="#" class="btn btn-primary btn-md back-to-top" role="button" title="Click to return on the top page" data-toggle="tooltip" data-placement="left"><span class="glyphicon glyphicon-chevron-up"></span></a>

  <div class="vehicle-instructions bg-lt-gray">
    <div class="row no-margin">
      <div class="col-sm-12">
        <ol>
          <li><span class="li-style">Once you've found your perfect home, visit any realtor to negotiate your purchase or sell as normal.</span></li>
          <li><span class="li-style">Return to HomePathRewards.com within 60 days and click on 'Get My Check'.</span></li>
          <li><span class="li-style">Receive your check in the mail to spend on whatever you want!</span></li>
        </ol>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/welcome/eligible.html.erb
<!DOCTYPE html>

<html>

<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<head>
  <title>HomePath</title>
</head>
<body>
<div class="container">
<div class="header-image">
  <picture>
    <source media="(max-width: 600px)" srcset="/Content/Images/V2/header-hyundai-mobile.jpg">
    <%= image_tag "jamr_carousal.jpg" %>
  </picture>
  <div class="header-scroll-overlay-container">
    <div id="header-scroll-overlay" class="text-center">
      <p>SCROLL TO SEE MORE<br /><%= image_tag "chevrons.png" %></p>
    </div>
  </div>
</div>
<div class="search-content bg-lt-gray">
  <div class="row no-margin">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1 text-center">
      <h1 class="orange">AM I ELIGIBLE?</h1>
      <p>HomePath is an exclusive home reward program that is only available to members of participating organizations and common household residents of members of those organizations.</p>
      <p>You may receive this perk through a number of organizations such as your <strong><span class="orange">CREDIT UNION</span>, <span class="orange">BANK</span>, <span class="orange">EMPLOYER</span>, <span class="orange">INSURANCE COMPANY</span>, <span class="orange">BENEFIT PROVIDER</span>, <span class="orange">ASSOCIATION</span></strong>, or <strong><span class="orange">MEMBERSHIP GROUP</span>.</strong> </p>
      <p>Use the search box below to check your eligibility.</p>
    </div>
  </div>
  <div class="row no-margin margin-top-30">
    <div class="col-xs-12 col-sm-4">
      <label>ORGANIZATION TYPE</label>
      <select id="AffiliationType" name="AffiliationType"><option value="">SELECT</option>
        <option value="Association">Associations or Membership</option>
        <option value="Financial Institution">Financial Institution (Credit Union or Bank)</option>
        <option value="Employer">Employer</option>
        <option value="Insurance">Insurance Company</option>
      </select>
    </div>
    <div class="col-xs-12 col-sm-5">
      <label>ORGANIZATION NAME</label>
      <input class="margin-top-7" id="OrganizationName" name="OrganizationName" onkeypress="validatecharacters(event)" type="text" value="" />
    </div>
    <div class="col-xs-12 col-sm-3">
      <div class="search-align">
        <input type="button" value="SEARCH" class="search" />
      </div>
    </div>
  </div>
  <div class="row no-margin">
    <div class="col-sm-12" id="search-results"></div>
    <div class="col-sm-12" id="search-error">Please enter at least the first 3 characters of your association group.</div>
  </div>
</div>

<!--<div class="dk-contact bg-dk-gray text-center">-->
  <!--<div class="row no-margin dk-contact-margin">-->
    <!--<div class="col-sm-12">-->
      <!--<p class="orange">If you don’t find your company or organization, please contact us:</p>-->
    <!--</div>-->
  <!--</div>-->
  <!--<div class="row no-margin dk-contact-icon-margin">-->
    <!--<div class="col-sm-12 col-md-6 contact-right">-->
      <!--<p class="kerning dk-contact-icon-margin dk-contact-icon"><img src="../Content/Images/V2/email.png" alt="Email" /> <a href="mailto:info@HomePathRewards.com" style="color:inherit;"><strong>INFO@HomePathRewards.COM</strong></a></p>-->
    <!--</div>-->
    <!--<div class="col-sm-12 col-md-6 contact-left">-->
      <!--<p class="kerning dk-contact-icon"><img src="../Content/Images/V2/phone.png" alt="Phone" /> <a href="tel:888-982-6687" style="color:inherit;"><strong>888-98-BONUS (26687)</strong></a></p>-->
    <!--</div>-->
  <!--</div>-->
<!--</div>-->
</div>


<script type="text/javascript">
    $(document).ready(function () {
        var isIE11 = !!window.MSInputMethodContext && !!document.documentMode;
        if (isIE11 && window.matchMedia("(max-width: 768px)").matches) {
            $("#make-logo-mobile").show();
            $("#make-logo-desktop").hide();
        }
    });
    if (matchMedia) {
        const mq = window.matchMedia("(max-width: 768px)");
        mq.addListener(WidthChange);
        WidthChange(mq);
    }
    function WidthChange(mq) {
        var isIE11 = !!window.MSInputMethodContext && !!document.documentMode;

        if (mq.matches || (isIE11 && window.matchMedia("(max-width: 768px)").matches)) {
            $("#make-logo-mobile").show();
            $("#make-logo-desktop").hide();
        } else {
            $("#make-logo-mobile").hide();
            $("#make-logo-desktop").show();
        }
    }
</script>

<script>
    $(document).ready(function () {
        var pathname = (window.location.pathname);
        $('.nav a').each(function () {
            var currentlink = "";
            if ($(this).attr('href').indexOf("?") === -1)
                currentlink = $(this).attr('href');
            else
                currentlink = $(this).attr('href').substring(0, $(this).attr('href').indexOf("?"));
            if (currentlink === pathname) {
                $(this).addClass("nav-active")
            }
        });
        if (pathname.indexOf("/Home/Register") != -1 || pathname.indexOf("/Home/VehicleInformation") != -1 || pathname.indexOf("Home/Eligibility/index.html") != -1 || pathname.indexOf("Home/Survey/index.html") != -1 || pathname == "/Home/Confirmation" || pathname.indexOf("/Home/Resubmit") != -1)
            $("body").addClass("bg-dk-gray");
    });
</script>
</body>
</html>